"""Optional generic PyTorch runtime, trainer, profiler, and state utilities.

Install the ``torch`` extra before importing this package.
"""

from __future__ import annotations

from mammoth.torch.backend import (
    TorchBackendConfig,
    TorchBackendState,
    TorchSeedPolicy,
    apply_torch_backend_config,
    apply_torch_seed_policy,
    configured_torch_backend,
    current_torch_backend_state,
)
from mammoth.torch.batch import move_batch_to_device
from mammoth.torch.callbacks import Callback, EarlyStopping
from mammoth.torch.checkpoint import (
    AsyncCheckpointPublisher,
    CheckpointArtifact,
    CheckpointCaptureMode,
    CheckpointComponent,
    CheckpointInspection,
    CheckpointMode,
    CheckpointPlan,
    CheckpointPublication,
    CheckpointRole,
    CheckpointSavePolicy,
    PublishedCheckpoint,
    RestoreOptions,
    StateRegistry,
    TrainerCheckpointContext,
    TrainerCheckpointPolicy,
    TrainerCheckpointRestore,
    TrainerCheckpointWriters,
    checkpoint_payload,
    publish_checkpoint_plan,
    restore_checkpoint,
)
from mammoth.torch.metrics import (
    MetricAccumulator,
    MetricRoute,
    MetricSpec,
    StatefulMetric,
)
from mammoth.torch.profiling import (
    CudaMemoryStats,
    LatencySummary,
    NamedPhaseProfiler,
    OperationProfile,
    PhaseLatencySummary,
    ProfileConfig,
    ProfileReport,
    ProfileTiming,
    ThroughputSummary,
    TorchRuntimeOptions,
    TorchRuntimeState,
    collect_cuda_memory_stats,
    current_torch_runtime_state,
    normalize_operation_profiles,
    profile_callable,
    reset_cuda_peak_memory_stats,
    summarize_latency,
    summarize_output_value,
    synchronize_device,
    torch_runtime_options,
    write_profile_report,
)
from mammoth.torch.runtime import (
    ExecutionRequest,
    ExecutionSession,
    Runtime,
    RuntimeConfig,
    initialize_runtime,
)
from mammoth.torch.scheduling import (
    AccumulationPlan,
    AccumulationPolicy,
    UniformAccumulationPolicy,
    WarmupLinearLR,
    WeightedAccumulationPolicy,
    WeightedDistributedBatchSampler,
    WeightedTaskAssignment,
    allocate_weighted_tasks,
    weighted_partition_counts,
    weighted_partition_indices,
)
from mammoth.torch.state import TrainerState
from mammoth.torch.trainer import (
    StepContext,
    StepFunction,
    StepOutput,
    TorchCompileConfig,
    Trainer,
    TrainerConfig,
    TrainerResult,
)

__all__ = [
    "AsyncCheckpointPublisher",
    "AccumulationPlan",
    "AccumulationPolicy",
    "Callback",
    "CheckpointArtifact",
    "CheckpointCaptureMode",
    "CheckpointComponent",
    "CheckpointInspection",
    "CheckpointMode",
    "CheckpointPlan",
    "CheckpointPublication",
    "CheckpointRole",
    "CheckpointSavePolicy",
    "CudaMemoryStats",
    "EarlyStopping",
    "LatencySummary",
    "NamedPhaseProfiler",
    "MetricAccumulator",
    "MetricRoute",
    "MetricSpec",
    "OperationProfile",
    "PhaseLatencySummary",
    "ProfileConfig",
    "ProfileReport",
    "ProfileTiming",
    "PublishedCheckpoint",
    "RestoreOptions",
    "StateRegistry",
    "StatefulMetric",
    "StepContext",
    "StepFunction",
    "StepOutput",
    "Trainer",
    "TrainerConfig",
    "TrainerCheckpointContext",
    "TrainerCheckpointPolicy",
    "TrainerCheckpointRestore",
    "TrainerCheckpointWriters",
    "TrainerResult",
    "TrainerState",
    "TorchCompileConfig",
    "ExecutionRequest",
    "Runtime",
    "ExecutionSession",
    "RuntimeConfig",
    "TorchRuntimeOptions",
    "TorchRuntimeState",
    "TorchBackendConfig",
    "TorchBackendState",
    "TorchSeedPolicy",
    "ThroughputSummary",
    "UniformAccumulationPolicy",
    "WarmupLinearLR",
    "WeightedAccumulationPolicy",
    "WeightedDistributedBatchSampler",
    "WeightedTaskAssignment",
    "allocate_weighted_tasks",
    "checkpoint_payload",
    "apply_torch_backend_config",
    "apply_torch_seed_policy",
    "collect_cuda_memory_stats",
    "configured_torch_backend",
    "current_torch_backend_state",
    "current_torch_runtime_state",
    "initialize_runtime",
    "move_batch_to_device",
    "normalize_operation_profiles",
    "publish_checkpoint_plan",
    "profile_callable",
    "restore_checkpoint",
    "reset_cuda_peak_memory_stats",
    "summarize_latency",
    "summarize_output_value",
    "synchronize_device",
    "torch_runtime_options",
    "weighted_partition_counts",
    "weighted_partition_indices",
    "write_profile_report",
]
