"""Framework-neutral run identity, artifact, provenance, and event APIs.

Higher Mammoth layers depend on this package; it imports only the Python
standard library and never imports model, dataset, or project code.
"""

from __future__ import annotations

from mammoth.core.artifacts import (
    ArtifactChangedError,
    ArtifactReadSession,
    ArtifactReceipt,
    ArtifactVerificationError,
    PreparedArtifact,
    atomic_publish,
    atomic_write_bytes,
    atomic_write_json,
    atomic_write_text,
    discard_prepared_artifact,
    inspect_artifact,
    open_artifact_session,
    prepare_artifact,
    publish_prepared_artifact,
    verify_artifact,
)
from mammoth.core.events import (
    EXECUTION_EVENT_SCHEMA_VERSION,
    EventName,
    ExecutionEvent,
    ExecutionEventReadError,
    ExecutionEventTailReader,
    ExecutionEventWriter,
    iter_execution_events,
    read_execution_events,
)
from mammoth.core.execution import (
    EXECUTION_ID_ENV,
    INVOCATION_KIND_ENV,
    LOGICAL_RUN_LEASE_FILENAME,
    PHASE_ENV,
    RUN_NAME_ENV,
    ExecutionContext,
    ExecutionMetadata,
    LogicalRunLease,
    claim_logical_run_lease,
    create_execution_context,
    execution_id_from_environment,
    generate_execution_id,
    join_execution_context,
    latest_execution_id,
    sanitize_command,
    sanitize_metadata_fields,
    sanitize_reference,
    validate_resume_checkpoint_sha256,
)
from mammoth.core.identity import validate_execution_id, validate_run_name
from mammoth.core.layout import RunLayout
from mammoth.core.pipeline import (
    BackgroundPipelineError,
    BackgroundPipelineResult,
    BackgroundPipelineSubmission,
    BoundedBackgroundPipeline,
)
from mammoth.core.transactions import (
    ArtifactKind,
    ArtifactTransactionConflictError,
    ArtifactTransactionError,
    ArtifactTransactionPlan,
    ArtifactTransactionRecoveryError,
    ArtifactTransactionRecoveryRequired,
    ArtifactTransactionResult,
    ArtifactTransactionValidationError,
    ArtifactValidator,
    PublicationMode,
    RecoveryPolicy,
    TransactionArtifact,
    TransactionArtifactSpec,
    TransactionObjectIdentity,
    build_artifact_transaction_plan,
    claim_artifact_transaction_leases,
    move_directory_into_transaction_stage,
    publish_artifact_transaction,
    recover_artifact_transaction,
    seal_artifact_transaction,
    stage_transaction_file,
    transaction_journal_path,
    transaction_stage_path,
)

__all__ = [
    "BackgroundPipelineError",
    "BackgroundPipelineResult",
    "BackgroundPipelineSubmission",
    "BoundedBackgroundPipeline",
    "ArtifactChangedError",
    "ArtifactReadSession",
    "ArtifactKind",
    "ArtifactReceipt",
    "ArtifactVerificationError",
    "ArtifactTransactionConflictError",
    "ArtifactTransactionError",
    "ArtifactTransactionPlan",
    "ArtifactTransactionRecoveryError",
    "ArtifactTransactionRecoveryRequired",
    "ArtifactTransactionResult",
    "ArtifactTransactionValidationError",
    "ArtifactValidator",
    "EXECUTION_EVENT_SCHEMA_VERSION",
    "EXECUTION_ID_ENV",
    "EventName",
    "ExecutionContext",
    "ExecutionEvent",
    "ExecutionEventReadError",
    "ExecutionEventTailReader",
    "ExecutionEventWriter",
    "ExecutionMetadata",
    "INVOCATION_KIND_ENV",
    "LOGICAL_RUN_LEASE_FILENAME",
    "LogicalRunLease",
    "PHASE_ENV",
    "PreparedArtifact",
    "PublicationMode",
    "RUN_NAME_ENV",
    "RecoveryPolicy",
    "RunLayout",
    "TransactionArtifact",
    "TransactionArtifactSpec",
    "TransactionObjectIdentity",
    "atomic_publish",
    "atomic_write_bytes",
    "atomic_write_json",
    "atomic_write_text",
    "build_artifact_transaction_plan",
    "claim_logical_run_lease",
    "claim_artifact_transaction_leases",
    "create_execution_context",
    "discard_prepared_artifact",
    "execution_id_from_environment",
    "generate_execution_id",
    "inspect_artifact",
    "iter_execution_events",
    "join_execution_context",
    "latest_execution_id",
    "move_directory_into_transaction_stage",
    "open_artifact_session",
    "prepare_artifact",
    "publish_prepared_artifact",
    "publish_artifact_transaction",
    "read_execution_events",
    "recover_artifact_transaction",
    "sanitize_command",
    "sanitize_metadata_fields",
    "sanitize_reference",
    "seal_artifact_transaction",
    "stage_transaction_file",
    "transaction_journal_path",
    "transaction_stage_path",
    "validate_execution_id",
    "validate_resume_checkpoint_sha256",
    "validate_run_name",
    "verify_artifact",
]
